apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-deploy
  labels:
    app: sso
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sso
  template:
    metadata:
      labels:
        app: sso
    spec:
      containers:
      - name: sso-counter
        image: gcr.io/devops-tt/sso:v3
        ports:
        - containerPort: 8008
