apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deploy
  labels:
    app: activemq
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq-counter
        image: rmohr/activemq
        ports:
        - containerPort: 61616
