apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-counter
        image: gcr.io/devops-tt/api:v1
        ports:
        - containerPort: 8080
#        volumeMounts:
#            # name must match the volume name below
#            - name: nfs
#              mountPath: "/opt/teamtask-anexos"
#      volumes:
#      - name: nfs
#        persistentVolumeClaim:
#          claimName: nfs
#